### ISSUE TITLE
Windows - repackage fails

### ISSUE THREAD

**Issue by n1t1nv3rma** [sisatech/vcli#14]
Hi, repackage failing on the windows using vcli

C:\cygwin\home\nverma\vorteil>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 5653-9317

 Directory of C:\cygwin\home\nverma\vorteil

04/11/2017  12:59 PM    <DIR>          .
04/11/2017  12:59 PM    <DIR>          ..
04/11/2017  12:41 PM    <DIR>          helloworld
03/11/2017  04:46 PM        54,049,061 vcli.exe
               2 File(s)     54,049,327 bytes
               3 Dir(s)  138,860,404,736 bytes free

C:\cygwin\home\nverma\vorteil>
C:\cygwin\home\nverma\vorteil>
**C:\cygwin\home\nverma\vorteil>vcli package helloworld --icon helloworld/vorteil.png**
Using ELF binary: helloworld/helloworld
Using config file: helloworld/helloworld.vcfg
Using files: helloworld/helloworld.files
Configuration Summary:
  Vorteil kernel 0.1.9
  72 MiB virtual disk with ext2 partition
  1 network card
Merging 1 directories
  helloworld/helloworld.files
**Error: open /: Access is denied.**

C:\cygwin\home\nverma\vorteil>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 5653-9317

 Directory of C:\cygwin\home\nverma\vorteil

04/11/2017  12:59 PM    <DIR>          .
04/11/2017  12:59 PM    <DIR>          ..
04/11/2017  12:41 PM    <DIR>          helloworld
**04/11/2017  12:59 PM               266 helloworld.vorteil**
03/11/2017  04:46 PM        54,049,061 vcli.exe
               3 File(s)     54,049,593 bytes
               3 Dir(s)  138,860,367,872 bytes free

C:\cygwin\home\nverma\vorteil>

As you can see the file was created but only 266 bytes in size. I have tried from Windows CMD as well as from Cygwin same error.

2) For some reason vcli always throws following errors if run under Cygwin even though the command always works.

 nverma@RNP233 ~/vorteil
$ vcli.exe unpack helloworld.vorteil
**The Vorteil home directory is corrupt. Starting from scratch...
Failed to lookup latest version information: Get https://storage.googleapis.com/vorteil/system/manifest.txt: proxyconnect tcp: dial tcp 127.0.0.1:39999: connectex: No connection could be made because the target machine actively refused it.**

nverma@RNP233 ~/vorteil

**Comment by alankm** [comment]
Thanks for the detailed bug report. There seems to be two things going on here:

1) The error repackaging: "open /: Access is denied". By the look of things this may be a bug that slipped through that only occurs on windows. I will try to replicate the error to confirm.

2) The error in Cygwin: "The Vorteil home directory is corrupt [...]". I'm not completely sure what the cause of this issue is, but the error message suggests that it is perhaps caused by some strange proxy settings on your end. 

VCLI keeps a directory where it stores the various data that it uses, that we call the "Vorteil home directory". The first time you use VCLI it will try to construct this directory, which includes saving some information retrieved from Sisa-Tech's online repository (information such as what the latest version of the kernel is). If VCLI launches and the Vorteil home directory is missing files, it will report that "The Vorteil home directory is corrupt", and attempt to rebuild it.

It looks like VCLI is failing to connect to the online repository, and as a result it is not able to get all of the information it needs to properly initialize the Vorteil home directory. The error message seems fairly clear: Failed to lookup latest version information: "Get https://storage.googleapis.com/vorteil/system/manifest.txt: proxyconnect tcp: dial tcp 127.0.0.1:39999: connectex: No connection could be made because the target machine actively refused it."

It looks like you have some sort of proxy settings that are preventing you from connecting to Sisa-Tech's online repository.

**Comment by alankm** [comment]
The latest commit fixes the first issue (Error 1) on Windows.

**Comment by n1t1nv3rma** [comment]
Thanks a lot for fixing this so fast. I'll download and test the new version. 

And you were **dead right**, please ignore the Error 2, it was due to my office proxy settings!  :)

**Comment by n1t1nv3rma** [comment]
I can confirm the packing issues is fixed on Windows/Cygwin now 💯 

Though I am not able to Deploy my App - it just hangs/timeout on the "Preparing Deployment" screen - perhaps permission or service issue at this stage. 

Thanks for your help!

**Comment by alankm** [comment]
Is this on go-vorteil.io?

**Comment by n1t1nv3rma** [comment]
Yes! Thanks 


Regards

On Tuesday, November 7, 2017, 12:57 pm, alankm <notifications@github.com> wrote:


Is this on go-vorteil.io?

**Comment by alankm** [comment]
I've taken a look, but I can't see any reason for your problem. It seems to me that you're probably trying to follow the quick-start guide. I've just followed it myself on a Windows machine and had no issues.

If you'd like, you can send an email to support@vorteil.io for better help with go-vorteil.io. If the package you created is smaller than 15 MiB, you can upload it to that email address and we will be able to look more deeply into what the issue might be.
